api/urls.py
from django.urls import path

from . import views

app_name = 'api'
urlpatterns = [
    path('search', views.SearchDataAPI.as_view(), name='search'),
    path('upload', views.UploadJsonAPI.as_view(), name='upload'),
    path('download/<int:pk>', views.DownloadJsonAPI.as_view(), name='download'),

]

dashboard/urls.py
from django.urls import path

from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('data/<int:pk>', views.DataDetailView.as_view(), name='detail'),
    path('data/download/<int:pk>', views.DownloadData.as_view(), name='download'),
    path('add', views.AddDataView.as_view(), name='add_data'),
    path('login', views.UserLoginView.as_view(), name='user_login'),
    path('logout', views.LogoutView.as_view(), name='user_logout'),
]

laboratory_django/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('json/', include('json_handler.urls')),
    path('api/', include('api.urls')),
    path('', include('dashboard.urls')),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api-doc/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms


class UserLoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput({'placeholder': '  ', 'dir': 'auto',
                                'class': 'floating-input form-control'}), min_length=1)
    password = forms.CharField(widget=forms.PasswordInput({'placeholder': '  ', 'dir': 'auto',
                                                           'class': 'floating-input form-control'}))


class JsonUploadForm(forms.Form):
    author = forms.CharField(
        widget=forms.TextInput({'placeholder': 'Author name', 'dir': 'auto',
                                'class': 'form-control'}), min_length=1)
    upload = forms.FileField(widget=forms.FileInput({'class': 'custom-file-input', 'id': 'inputGroupFile01'}))

dashboard/views.py
import json

from django.contrib import messages
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, DetailView

from dashboard.forms import UserLoginForm, JsonUploadForm
from dashboard.utils import get_search_results, handle_merge
from json_handler.models import JSONData
from laboratory_django import settings


class UserLoginView(View):
    template_name = 'dashboard/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse('dashboard:dashboard'))
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        login_form = UserLoginForm()
        context = {
            'form': login_form,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        login_form = UserLoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            user: User = User.objects.filter(username__exact=username).first()
            if user is not None:
                if not user.is_active:
                    login_form.add_error('password', 'This account is not active')
                else:
                    is_password_correct = user.check_password(password)
                    if is_password_correct:
                        login(request, user)
                        return redirect(reverse('dashboard:dashboard'))
                    else:
                        login_form.add_error('password', 'Username or Password incorrect')
            else:
                login_form.add_error('password', 'Username or Password incorrect')

        context = {
            'form': login_form,
        }
        return render(request, self.template_name, context)


@method_decorator(login_required, name='dispatch')
class LogoutView(View):

    def get(self, request):
        logout(request)
        return redirect(reverse('dashboard:user_login'))


@method_decorator(login_required, name='dispatch')
class DashboardView(ListView):
    template_name = 'dashboard/index.html'
    model = JSONData
    context_object_name = 'datas'
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_count'] = JSONData.objects.count()
        search_term = self.request.GET.get('q', '')
        context['q'] = search_term
        context['search_count'] = self.get_queryset().count()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        search_term = self.request.GET.get('q', '')
        if search_term:
            queryset = get_search_results(queryset, search_term)
        return queryset

    def post(self, request, *args, **kwargs):
        if 'action' in request.POST:
            action = request.POST.get('action_selector')
            ids = request.POST.get('ids')
            if ids != '':
                if action == 'delete_selected':
                    ids_list = json.loads(ids)
                    count = len(ids_list)
                    JSONData.objects.filter(id__in=ids_list).delete()
                    messages.success(request, f"Successfully deleted {count} json data")
                    return redirect('dashboard:dashboard')
                    # messages.warning(request, "Your account expires in three days.")
                    # messages.error(request, "Document deleted.")
                elif action == 'merge_selected':
                    ids_list = json.loads(ids)
                    file_name = handle_merge(ids_list)
                    return redirect('json:download', name=file_name)
                else:
                    messages.error(request, f"No action selected.")
                    return redirect('dashboard:dashboard')
            else:
                messages.error(request,
                               f"Items must be selected in order to perform actions on them. No items have been changed")
                return redirect('dashboard:dashboard')

        return render(request, self.template_name)


@method_decorator(login_required, name='dispatch')
class DataDetailView(DetailView):
    template_name = 'dashboard/detail.html'
    model = JSONData
    context_object_name = 'data'

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        obj = get_object_or_404(JSONData, pk=pk)
        return obj


@method_decorator(login_required, name='dispatch')
class AddDataView(View):
    template_name = 'dashboard/add.html'
    form_class = JsonUploadForm

    def get(self, request):
        context = {
            'form': self.form_class(),
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            author = request.POST.get('author')
            new_json_file = request.FILES['upload']
            try:
                new_data = json.loads(new_json_file.read().decode('utf-8'))

                for key, value in new_data.items():
                    exists = False
                    for obj in JSONData.objects.all():
                        if key in obj.data and obj.data[key] == value:
                            exists = True
                            break

                    if not exists:
                        JSONData.objects.create(upload=new_json_file, data={key: value}, author=author)

                messages.success(request, 'JSON data uploaded successfully.')
                return redirect('dashboard:add_data')

            except json.JSONDecodeError:
                messages.error(request, 'Uploaded file is not a valid JSON.')
            except Exception as e:
                messages.error(request, f'An error occurred: {str(e)}')

        context = {
            'form': form,
        }
        return render(request, self.template_name, context)


@method_decorator(login_required, name='dispatch')
class DownloadData(View):
    def get(self, request, pk):
        try:
            obj = JSONData.objects.get(pk=pk)
            data = obj.data
            json_data = json.dumps(data, indent=4)

            temp_file_path = settings.MEDIA_ROOT + 'files'
            with open(temp_file_path, 'w') as f:
                f.write(json_data)

            with open(temp_file_path, 'rb') as f:
                response = HttpResponse(f.read(), content_type='application/json')
                response['Content-Disposition'] = f'attachment; filename="{obj.pk}.json"'
            return response

        except JSONData.DoesNotExist:
            return JsonResponse({"data": "File does not exist"}, status=404)

        except Exception as e:
            return JsonResponse({"error": str(e)}, status=400)

dashboard/templates/shared/base.html
<!doctype html>
<html lang="en">
<head>
    {% include 'shared/head_refrances.html' %}
    {% block extra_head_ref %}{% endblock %}

    <title>{% block title %}{% endblock %}</title>
</head>
<body class=" color-light ">
<!-- loader Start -->
<div id="loading">
    <div id="loading-center">
    </div>
</div>

<div class="wrapper">
    {% if request.resolver_match.url_name != 'user_login' %}
        {% include 'shared/sidebar.html' %}
        {% include 'shared/header.html' %}


        <div class="content-page">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        {% block content %}{% endblock %}
                    </div>
                </div>
            </div>
        </div>

        {% include 'shared/footer.html' %}
        {% else %}
        {% block login_content %}{% endblock %}
    {% endif %}
    {% include 'shared/footer_refrances.html' %}
    {% block extra_footer_ref %}{% endblock %}

</div>

dashboard/templates/shared/footer.html
    <footer class="iq-footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6">
                    <ul class="list-inline mb-0">
                    </ul>
                </div>
                <div class="col-lg-6 text-right">
                </div>
            </div>
        </div>
    </footer>

dashboard/templates/shared/footer_refrances.html
{% load static %}
<!-- Backend Bundle JavaScript -->
<script src="{% static 'js/backend-bundle.min.js' %}"></script>

<!-- Table Treeview JavaScript -->
<script src="{% static 'js/table-treeview.js' %}"></script>

<!-- Chart Custom JavaScript -->
<script src="{% static 'js/customizer.js' %}"></script>

<!-- Chart Custom JavaScript -->
<script async src="{% static 'js/chart-custom.js' %}"></script>
<!-- Chart Custom JavaScript -->
<script async src="{% static 'js/slider.js' %}"></script>

<!-- app JavaScript -->
<script src="{% static 'js/app.js' %}"></script>

<script src="{% static 'vendor/moment.min.js' %}"></script>

dashboard/templates/shared/head_refrances.html
{% load static %}
<!-- Favicon -->
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
<link rel="stylesheet" href="{% static 'css/backend-plugin.min.css' %}">
<link rel="stylesheet" href="{% static 'css/backend.css' %}">
<link rel="stylesheet" href="{% static 'vendor/line-awesome/dist/line-awesome/css/line-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/remixicon/fonts/remixicon.css' %}">

<link rel="stylesheet" href="{% static 'vendor/tui-calendar/tui-calendar/dist/tui-calendar.css' %}">
<link rel="stylesheet" href="{% static 'vendor/tui-calendar/tui-date-picker/dist/tui-date-picker.css' %}">
<link rel="stylesheet" href="{% static 'vendor/tui-calendar/tui-time-picker/dist/tui-time-picker.css' %}">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

dashboard/templates/shared/header.html
{% load static %}
<div class="iq-top-navbar">
    <div class="iq-navbar-custom">
        <nav class="navbar navbar-expand-lg navbar-light p-0">
            <div class="iq-navbar-logo d-flex align-items-center justify-content-between">
                <i class="ri-menu-line wrapper-menu"></i>
                <a href="{% url 'dashboard:dashboard' %}" class="header-logo">
                    <h4 class="logo-title text-uppercase">Laboratory</h4>

                </a>
            </div>
            <div class="navbar-breadcrumb">
                <h5>Dashboard</h5>
            </div>
            <div class="d-flex align-items-center">
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-label="Toggle navigation">
                    <i class="ri-menu-3-line"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto navbar-list align-items-center">
                        <li class="nav-item nav-icon dropdown caption-content">
                            <a href="#" class="search-toggle dropdown-toggle  d-flex align-items-center"
                               id="dropdownMenuButton4"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <img src="{% static 'images/user/user2.jpg' %}" class="img-fluid rounded-circle"
                                     alt="user">
                                <div class="caption ml-3">
                                    <h6 class="mb-0 line-height">{{ request.user.username }}<i
                                            class="las la-angle-down ml-2"></i></h6>
                                </div>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-right border-none"
                                aria-labelledby="dropdownMenuButton">
                                {% if request.user.is_superuser %}
                                    <li class="dropdown-item  d-flex svg-icon">
                                        <svg class="svg-icon mr-0 text-primary" id="h-05-p" width="20"
                                             xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                             stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                  d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                                        </svg>
                                        <a href="/admin">Admin Panel</a>
                                    </li>
                                {% endif %}
                                <li class="dropdown-item  d-flex svg-icon">
                                    <svg class="svg-icon mr-0 text-primary" id="h-05-p" width="20"
                                         xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                         stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                              d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"/>
                                    </svg>
                                    <a href="{% url 'dashboard:user_logout' %}">Logout</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</div>

dashboard/templates/shared/sidebar.html
{% load static %}
<div class="iq-sidebar  sidebar-default ">
    <div class="iq-sidebar-logo d-flex align-items-center">
        <a href="{% url 'dashboard:dashboard' %}" class="header-logo">
            <img src="{% static 'images/logo.svg' %}" alt="logo">
            <h3 class="logo-title light-logo">Lab</h3>
        </a>
        <div class="iq-menu-bt-sidebar ml-0">
            <i class="las la-bars wrapper-menu"></i>
        </div>
    </div>
    <div class="data-scrollbar" data-scroll="1">
        <nav class="iq-sidebar-menu">
            <ul id="iq-sidebar-toggle" class="iq-menu">
                <li {% if request.resolver_match.url_name == 'dashboard' %}class="active"{% endif %}>
                    <a href="{% url 'dashboard:dashboard' %}" class="svg-icon">
                        <svg class="svg-icon" width="25" height="25" xmlns="http://www.w3.org/2000/svg"
                             viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                             stroke-linecap="round" stroke-linejoin="round">
                            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
                            <polyline points="14 2 14 8 20 8"></polyline>
                            <line x1="16" y1="13" x2="8" y2="13"></line>
                            <line x1="16" y1="17" x2="8" y2="17"></line>
                            <polyline points="10 9 9 9 8 9"></polyline>
                        </svg>
                        <span class="ml-4">Data Entries</span>
                    </a>
                </li>
                <li {% if request.resolver_match.url_name == 'add_data' %}class="active"{% endif %}>
                    <a href="{% url 'dashboard:add_data' %}" class="svg-icon">
                        <svg class="svg-icon" width="25" height="25" xmlns="http://www.w3.org/2000/svg"
                             viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                             stroke-linecap="round" stroke-linejoin="round">
                            <path d="M24 10h-10v-10h-4v10h-10v4h10v10h4v-10h10z"/>
                        </svg>
                        <span class="ml-4">Add New Data</span>
                    </a>
                </li>
            </ul>
        </nav>
        <div class="pt-5 pb-2"></div>
    </div>
</div>