api/urls.py
from django.urls import path

from . import views

app_name = 'api'
urlpatterns = [
    path('search', views.SearchDataAPI.as_view(), name='search'),
    path('upload', views.UploadJsonAPI.as_view(), name='upload'),
    path('download/<int:pk>', views.DownloadJsonAPI.as_view(), name='download'),

]

dashboard/urls.py
from django.urls import path

from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('data/<int:pk>', views.DataDetailView.as_view(), name='detail'),
    path('data/download/<int:pk>', views.DownloadData.as_view(), name='download'),
    path('add', views.AddDataView.as_view(), name='add_data'),
    path('login', views.UserLoginView.as_view(), name='user_login'),
    path('logout', views.LogoutView.as_view(), name='user_logout'),
]

laboratory_django/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('json/', include('json_handler.urls')),
    path('api/', include('api.urls')),
    path('', include('dashboard.urls')),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api-doc/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms


class UserLoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput({'placeholder': '  ', 'dir': 'auto',
                                'class': 'floating-input form-control'}), min_length=1)
    password = forms.CharField(widget=forms.PasswordInput({'placeholder': '  ', 'dir': 'auto',
                                                           'class': 'floating-input form-control'}))


class JsonUploadForm(forms.Form):
    author = forms.CharField(
        widget=forms.TextInput({'placeholder': 'Author name', 'dir': 'auto',
                                'class': 'form-control'}), min_length=1)
    upload = forms.FileField(widget=forms.FileInput({'class': 'custom-file-input', 'id': 'inputGroupFile01'}))

dashboard/views.py
import json

from django.contrib import messages
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, DetailView

from dashboard.forms import UserLoginForm, JsonUploadForm
from dashboard.utils import get_search_results, handle_merge
from json_handler.models import JSONData
from laboratory_django import settings


class UserLoginView(View):
    template_name = 'dashboard/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse('dashboard:dashboard'))
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        login_form = UserLoginForm()
        context = {
            'form': login_form,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        login_form = UserLoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            user: User = User.objects.filter(username__exact=username).first()
            if user is not None:
                if not user.is_active:
                    login_form.add_error('password', 'This account is not active')
                else:
                    is_password_correct = user.check_password(password)
                    if is_password_correct:
                        login(request, user)
                        return redirect(reverse('dashboard:dashboard'))
                    else:
                        login_form.add_error('password', 'Username or Password incorrect')
            else:
                login_form.add_error('password', 'Username or Password incorrect')

        context = {
            'form': login_form,
        }
        return render(request, self.template_name, context)


@method_decorator(login_required, name='dispatch')
class LogoutView(View):

    def get(self, request):
        logout(request)
        return redirect(reverse('dashboard:user_login'))


@method_decorator(login_required, name='dispatch')
class DashboardView(ListView):
    template_name = 'dashboard/index.html'
    model = JSONData
    context_object_name = 'datas'
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_count'] = JSONData.objects.count()
        search_term = self.request.GET.get('q', '')
        context['q'] = search_term
        context['search_count'] = self.get_queryset().count()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        search_term = self.request.GET.get('q', '')
        if search_term:
            queryset = get_search_results(queryset, search_term)
        return queryset

    def post(self, request, *args, **kwargs):
        if 'action' in request.POST:
            action = request.POST.get('action_selector')
            ids = request.POST.get('ids')
            if ids != '':
                if action == 'delete_selected':
                    ids_list = json.loads(ids)
                    count = len(ids_list)
                    JSONData.objects.filter(id__in=ids_list).delete()
                    messages.success(request, f"Successfully deleted {count} json data")
                    return redirect('dashboard:dashboard')
                    # messages.warning(request, "Your account expires in three days.")
                    # messages.error(request, "Document deleted.")
                elif action == 'merge_selected':
                    ids_list = json.loads(ids)
                    file_name = handle_merge(ids_list)
                    return redirect('json:download', name=file_name)
                else:
                    messages.error(request, f"No action selected.")
                    return redirect('dashboard:dashboard')
            else:
                messages.error(request,
                               f"Items must be selected in order to perform actions on them. No items have been changed")
                return redirect('dashboard:dashboard')

        return render(request, self.template_name)


@method_decorator(login_required, name='dispatch')
class DataDetailView(DetailView):
    template_name = 'dashboard/detail.html'
    model = JSONData
    context_object_name = 'data'

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        obj = get_object_or_404(JSONData, pk=pk)
        return obj


@method_decorator(login_required, name='dispatch')
class AddDataView(View):
    template_name = 'dashboard/add.html'
    form_class = JsonUploadForm

    def get(self, request):
        context = {
            'form': self.form_class(),
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            author = request.POST.get('author')
            new_json_file = request.FILES['upload']
            try:
                new_data = json.loads(new_json_file.read().decode('utf-8'))

                for key, value in new_data.items():
                    exists = False
                    for obj in JSONData.objects.all():
                        if key in obj.data and obj.data[key] == value:
                            exists = True
                            break

                    if not exists:
                        JSONData.objects.create(upload=new_json_file, data={key: value}, author=author)

                messages.success(request, 'JSON data uploaded successfully.')
                return redirect('dashboard:add_data')

            except json.JSONDecodeError:
                messages.error(request, 'Uploaded file is not a valid JSON.')
            except Exception as e:
                messages.error(request, f'An error occurred: {str(e)}')

        context = {
            'form': form,
        }
        return render(request, self.template_name, context)


@method_decorator(login_required, name='dispatch')
class DownloadData(View):
    def get(self, request, pk):
        try:
            obj = JSONData.objects.get(pk=pk)
            data = obj.data
            json_data = json.dumps(data, indent=4)

            temp_file_path = settings.MEDIA_ROOT + 'files'
            with open(temp_file_path, 'w') as f:
                f.write(json_data)

            with open(temp_file_path, 'rb') as f:
                response = HttpResponse(f.read(), content_type='application/json')
                response['Content-Disposition'] = f'attachment; filename="{obj.pk}.json"'
            return response

        except JSONData.DoesNotExist:
            return JsonResponse({"data": "File does not exist"}, status=404)

        except Exception as e:
            return JsonResponse({"error": str(e)}, status=400)

dashboard/templates/dashboard/add.html
{% extends 'shared/base.html' %}

{% block title %}
    Add New Data
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <div class="header-title">
                <h4 class="card-title">Add New Data</h4>
            </div>
        </div>
        <div class="card-body">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                        <div class="alert alert-danger" role="alert">
                            <div class="iq-alert-icon">
                                <i class="ri-close-fill"></i>
                            </div>
                            <div class="iq-alert-text">{{ message }}</div>
                        </div>
                    {% else %}
                        <div class="alert alert-success" role="alert">
                            <div class="iq-alert-icon">
                                <i class="ri-check-line"></i>
                            </div>
                            <div class="iq-alert-text">{{ message }}</div>
                        </div>
                    {% endif %}

                {% endfor %}
            {% endif %}
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="input-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="first">Author</span>
                        </div>
                        {{ form.author }}
                    </div>
                </div>
                <br>
                <div class="input-group mb-4">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Upload Json</span>
                    </div>
                    <div class="custom-file">
                        {{ form.upload }}
                        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary btn-new"><i class="ri-add-line"></i>Add and save</button>
            </form>
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/detail.html
{% extends 'shared/base.html' %}
{% load custom_filters %}
{% load static %}
{% block title %}{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <div class="card card-block card-stretch card-height print rounded">
            <div class="card-header d-flex justify-content-between bg-primary header-invoice">
                <div class="iq-header-title">
                    <h4 class="card-title mb-0">{{ data.json_file }} <span
                            class="badge badge-secondary">{{ data.author }}</span></h4>
                </div>
                <div class="invoice-btn">
                    <a href="{% url 'dashboard:download' pk=data.pk %}" class="btn btn-primary-dark"><i
                            class="las la-file-download"></i>Download</a>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="nav nav-pills mb-3 nav-fill" id="pills-tab-1" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="pills-home-tab-fill" data-toggle="pill"
                                   href="#pills-home-fill" role="tab" aria-controls="pills-home" aria-selected="true">Meta
                                    Data</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="pills-profile-tab-fill" data-toggle="pill"
                                   href="#pills-profile-fill" role="tab" aria-controls="pills-profile"
                                   aria-selected="false">Result</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="pills-contact-tab-fill" data-toggle="pill"
                                   href="#pills-contact-fill" role="tab" aria-controls="pills-contact"
                                   aria-selected="false">Json View</a>
                            </li>
                        </ul>
                        <div class="tab-content" id="pills-tabContent-1">
                            <div class="tab-pane fade show active" id="pills-home-fill" role="tabpanel"
                                 aria-labelledby="pills-home-tab-fill">
                                {% render_meta_data data.data %}
                                <div class="content">
                                    <div id="content-display"></div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="pills-profile-fill" role="tabpanel"
                                 aria-labelledby="pills-profile-tab-fill">
                                {% render_result_data data.data %}
                            </div>
                            <div class="tab-pane fade" id="pills-contact-fill" role="tabpanel"
                                 aria-labelledby="pills-contact-tab-fill">
                                <p>JSON VIEW</p>
                                <div id="jsoneditor" style="width: 100%; height: 100%;"></div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_head_ref %}
    <link href="{% static 'dist/jsoneditor.min.css' %}" media="all" rel="stylesheet">
    <script src="{% static '/dist/jsoneditor.min.js' %}"></script>
{% endblock %}

{% block extra_footer_ref %}

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var items = document.querySelectorAll('.nested-list > li, .nested-list .nested > li');

            items.forEach(function (item) {
                item.addEventListener('click', function (event) {
                    event.stopPropagation();
                    var contentId = item.getAttribute('data-content');
                    if (contentId) {
                        var content = document.getElementById(contentId).innerHTML;
                        document.getElementById('content-display').innerHTML = content;
                    }

                    var nestedList = item.querySelector('.nested');
                    if (nestedList) {
                        nestedList.classList.toggle('active');
                    }
                });
            });
        });
        // create the editor
        const container = document.getElementById("jsoneditor")
        var options = {
            mode: 'tree'
        };
        const editor = new JSONEditor(container, options)

        // set json
        const initialJson = {{ data.data|safe }}
            editor.set(initialJson)

        // get json
        const updatedJson = editor.get()

    </script>
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'shared/base.html' %}
{% load static %}
{% load custom_filters %}

{% block title %}
    Data Entries
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <div class="header-title">
                <h4 class="card-title">See All Datas</h4>
            </div>
        </div>
        <div class="card-body">
            <div class="input-group">
                <input type="text" placeholder="Type your query or select here" class="form-control"
                       aria-label="Text input with segmented dropdown button" id="input-tag">
                <form class="input-group-append" method="get">
                    <input type="hidden" size="40" name="q" value="{% if q %}{{ q }}{% endif %}" id="searchbar">
                    <button type="submit" class="btn btn-outline-primary">Search</button>
                    <button type="button" class="btn btn-primary dropone dropdown-toggle  dropdown-toggle-split"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="las la-angle-down"></i>
                    </button>
                    <div class="dropdown-menu" style="">
                        <a class="dropdown-item" onclick="indexUpdateInput('owner:')">Owner</a>
                        <a class="dropdown-item" onclick="indexUpdateInput('Abaqus-Version:')">Abaqus-Version</a>
                        <a class="dropdown-item" onclick="indexUpdateInput('Hash_Orientation:')">Hash_Orientation</a>
                        <a class="dropdown-item" onclick="indexUpdateInput('Texture_Type:')">Texture_Type</a>
                        <a class="dropdown-item" onclick="indexUpdateInput('Element_Number:')">Element_Number</a>
                        <a class="dropdown-item" onclick="indexUpdateInput('Grain_Number:')">Grain_Number</a>
                        <a class="dropdown-item" onclick="indexUpdateInput('Material_parameters:')">Material_parameters(Whole
                            array)</a>
                        <a class="dropdown-item" onclick="indexUpdateInput('Load_Type:')">Load_Type</a>
                        <a class="dropdown-item" onclick="indexUpdateInput('Stress_Type:')">Stress_Type</a>
                        <a class="dropdown-item" onclick="indexUpdateInput('Load_Descriptor:')">Load_Descriptor</a>
                        <a class="dropdown-item" onclick="indexUpdateInput('Hash_load:')">Hash_load</a>
                        <a class="dropdown-item" onclick="indexUpdateInput('Scaling_Factor:')">Scaling_Factor</a>
                        <a class="dropdown-item" onclick="indexUpdateInput('Max_Total_Strain:')">Max_Total_Strain</a>
                    </div>
                </form>
            </div>
            <div style="display: flex; gap: 5px;" id="tags">
            </div>
            <br>
            {% if q %}
                <span class="mt-2 badge border border-dark">{{ search_count }} results (<a href="{% url 'dashboard:dashboard' %}"
                                                                                           class="text-secondary">{{ total_count }} total</a>)</span>
            {% else %}
                <span class="mt-2 badge border border-dark">{{ total_count }} json datas</span>

            {% endif %}
            <br>
            <br>
            <div class="table-responsive">
                <table id="datatable" class="table data-table table-striped">
                    <thead>
                    <div style="width: 30%" class="input-group  mb-4">
                        <form method="post" action="">
                            {% csrf_token %}
                            <select class="custom-select" name="action_selector" id="actionSelector">
                                <option selected="" value="">Choose a action ...</option>
                                <option value="delete_selected">Delete selected json datas</option>
                                <option value="merge_selected">Merge selected json datas</option>
                            </select>
                            <input type="hidden" name="ids" id="ids" value="">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" id="go-button" type="submit" name="action">
                                    GO
                                </button>
                            </div>
                        </form>
                    </div>
                    {% if messages %}
                        {% for message in messages %}
                            {% if message.tags == 'error' %}
                                <div class="alert alert-danger" role="alert">
                                    <div class="iq-alert-icon">
                                        <i class="ri-close-fill"></i>
                                    </div>
                                    <div class="iq-alert-text">{{ message }}</div>
                                </div>
                            {% else %}
                                <div class="alert alert-success" role="alert">
                                    <div class="iq-alert-icon">
                                        <i class="ri-check-line"></i>
                                    </div>
                                    <div class="iq-alert-text">{{ message }}</div>
                                </div>
                            {% endif %}

                        {% endfor %}
                    {% endif %}

                    <tr class="ligth">
                        <th style="width: 1%;padding: 10px;text-align: center"><input type="checkbox" id="select-all">
                        </th>
                        <th>JSON FILE</th>
                        <th>AUTHOR</th>
                        <th>UPLOAD TIME</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if datas %}
                        {% for data in datas %}
                            <tr data-id="{{ data.id }}" class="main-row">
                                <td style="width: 1%;padding: 10px;text-align: center" class="checkbox-cell"><input
                                        type="checkbox" class="row-checkbox" value="{{ data.id }}"></td>
                                <td>{{ data.json_file }}</td>
                                <td>{{ data.author }}</td>
                                <td>{{ data.upload_time }}</td>
                                <td>
                                    <a href="{% url 'dashboard:detail' pk=data.pk %}">
                                        <button style="display: flex; gap: 4px" type="button"
                                                class="btn btn-outline-primary btn-sm mr-2">Detail<i
                                                class="ri-arrow-right-line"></i>
                                        </button>
                                    </a>
                                </td>
                            </tr>
                            <tr class="details-row" data-parent-id="{{ data.id }}">
                                <td></td>
                                <td colspan="1">
                                    <div class="p-1">
                                        <p><strong>Owner:</strong> {{ data.data|get_meta_data:"Owner" }}</p>
                                        <p><strong>Date:</strong> {{ data.data|get_meta_data:"Date" }}</p>
                                        <p><strong>Abaqus
                                            Version:</strong> {{ data.data|get_meta_data:"Abaqus-Version" }}
                                        </p>
                                        <p><strong>Hash
                                            Orientation:</strong> {{ data.data|get_meta_data:"Orientation.Hash_Orientation" }}
                                        </p>
                                        <p><strong>Texture
                                            Type:</strong> {{ data.data|get_meta_data:"Orientation.Texture_Type" }}</p>
                                        <p><strong>Material
                                            Identifier:</strong> {{ data.data|get_meta_data:"Material.Material_Identifier" }}
                                        </p>
                                        <p><strong>Element
                                            Number:</strong> {{ data.data|get_meta_data:"Element_Number" }}
                                        </p>
                                    </div>
                                </td>
                                <td colspan="1">
                                    <div class="p-1">

                                        <p><strong>Grain Number:</strong> {{ data.data|get_meta_data:"Grain_Number" }}
                                        </p>
                                        <p><strong>Load Type:</strong> {{ data.data|get_meta_data:"Load_Type" }}</p>
                                        <p><strong>Hash Load:</strong> {{ data.data|get_meta_data:"Hash_Load" }}</p>
                                        <p><strong>Load
                                            Descriptor:</strong> {{ data.data|get_meta_data:"Load_Descriptor" }}
                                        </p>
                                        <p><strong>Scaling
                                            Factor:</strong> {{ data.data|get_meta_data:"Scaling_Factor" }}
                                        </p>
                                        <p><strong>Max Total
                                            Strain:</strong> {{ data.data|get_meta_data:"Max_Total_Strain" }}</p>
                                    </div>
                                </td>
                                <td>
                                    <a href="{% url 'dashboard:detail' pk=data.pk %}">
                                        <button style="display: flex; gap: 4px" type="button"
                                                class="btn btn-outline-secondary btn-sm mr-2">
                                            Go to the entry page <i class="ri-arrow-right-line"></i>
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr class="odd">
                            <td valign="top" colspan="5" class="dataTables_empty">No data available in table</td>
                        </tr>
                    {% endif %}

                    </tbody>
                    <tfoot>
                    <tr>
                        <th></th>
                        <th>JSON FILE</th>
                        <th>AUTHOR</th>
                        <th>UPLOAD TIME</th>
                        <th></th>
                    </tr>
                    </tfoot>
                </table>
                <br>
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_footer_ref %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="{% static 'js/custom.js' %}"></script>
{% endblock %}